name: Windows RDP (Auto-Restart Persistent)

on:
  schedule:
    - cron: "0 */6 * * *"  # every 6 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 350

    steps:
      - name: Install QEMU
        run: |
          choco install qemu -y
          $env:Path += ";C:\Program Files\qemu"
          qemu-system-x86_64 --version

      - name: Prepare VM directory
        run: |
          mkdir C:\VM
          cd C:\VM

      - name: Download Windows Image
        run: |
          curl -L -o C:\VM\win.img https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img

      - name: Install and start Tailscale
        run: |
          choco install tailscale -y
          Start-Process -FilePath "C:\Program Files\Tailscale\tailscale.exe" `
            -ArgumentList "up --tskey-auth-kPXU45HmBi11CNTRL-BzBWEswXi6AXdCxQGJXE7AwAWqQe9Ard --hostname winvm --accept-routes --accept-dns=true" `
            -NoNewWindow -Wait
          & "C:\Program Files\Tailscale\tailscale.exe" status

      - name: Start Windows VM
        run: |
          $env:Path += ";C:\Program Files\qemu"
          qemu-system-x86_64 -m 4096 -cpu qemu64 -smp 4 `
            -drive file=C:\VM\win.img,format=qcow2 `
            -netdev user,id=net0,hostfwd=tcp::3389-:3389 `
            -device e1000,netdev=net0 `
            -boot d -display none

      - name: Keep VM alive
        run: |
          Write-Host "Windows VM running..."
          Start-Sleep -Seconds 21600  # 6 hours
